from Book import Book


book1 = Book(author='Marcus Perrie', name='Fighting back', issue_date='2019-01-01',genre='SciFi')
# print(book1.get_info())
# print(type(book1.get_info()))
print(str(book1))
print(repr(book1))
# print(type(str(book1)))
book2 = Book(author='Miranda Devis', name='Mystery sight', issue_date='2019-02-01', genre='Novel')
# print(book2.get_info())
print(str(book2))
book3 = Book(author='Marcus Perrie', name='Fighting back', issue_date='2019-01-01',genre='SciFi')
# print(book3.get_info())
print(str(book3))
book4 = eval(repr(book2))
print(str(book4))
# print()
# print(book1 == book2)
# print(book1 == book3)

print()
print(hash(book1))
print(hash(book2))
print(hash(book3))
print(hash(book4))

print(hash(book1) == hash(book2))
print(hash(book1) == hash(book3))
print()
print(hash(book2) == hash(book3))
print(hash(book2) == hash(book4))